#!/usr/bin/env python3
"""Finishes the /Models library after tools/lune/export_models.luau + tools/export_glb.py:

  - <Category>/_preview.png   contact sheet of every asset in that folder (thumbnail + name)
  - ASSET_INDEX.md            one table row per asset (generated - do not edit by hand)

usage: build_asset_index.py <workDir> <ModelsDir>
"""
import json, os, subprocess, sys, tempfile
from collections import defaultdict

from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
THUMB = 220
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"


def thumbnail(parts_json, size_studs, out_png):
    sx, sy, sz = size_studs
    span = max(sx, sy, sz, 1.0)
    at = (0, sy * 0.45, 0)
    d = span * 1.25
    eye = (d * 0.75, sy * 0.45 + d * 0.55, -d)
    subprocess.run([sys.executable, os.path.join(HERE, "render.py"), parts_json, out_png,
                    "--eye", ",".join(f"{v:.2f}" for v in eye), "--at", ",".join(f"{v:.2f}" for v in at),
                    "--fov", "40", "--size", f"{THUMB}x{THUMB}", "--sky", "246,240,232", "--fogcolor", "246,240,232"],
                   check=True, capture_output=True)


def contact_sheet(entries, out_png, work):
    cols = 6
    rows = (len(entries) + cols - 1) // cols
    label_h = 34
    sheet = Image.new("RGB", (cols * THUMB, rows * (THUMB + label_h)), (255, 250, 242))
    draw = ImageDraw.Draw(sheet)
    font = ImageFont.truetype(FONT, 13)
    with tempfile.TemporaryDirectory() as tmp:
        for i, meta in enumerate(entries):
            x, y = (i % cols) * THUMB, (i // cols) * (THUMB + label_h)
            src = os.path.join(work, meta["Category"].replace("/", "__") + "__" + meta["Name"] + ".json")
            if os.path.exists(src):
                png = os.path.join(tmp, "t.png")
                thumbnail(src, meta["SizeStuds"], png)
                sheet.paste(Image.open(png), (x, y))
            else:
                draw.rectangle([x + 10, y + 10, x + THUMB - 10, y + THUMB - 10], outline=(200, 190, 180), width=2)
                draw.text((x + THUMB / 2, y + THUMB / 2), "(effect)", fill=(140, 130, 120), font=font, anchor="mm")
            name = meta["Name"]
            if draw.textlength(name, font=font) > THUMB - 8:
                name = name[: max(4, int(len(name) * (THUMB - 8) / draw.textlength(name, font=font)) - 1)] + "…"
            draw.text((x + THUMB / 2, y + THUMB + label_h / 2), name, fill=(74, 58, 46), font=font, anchor="mm")
    sheet.save(out_png, optimize=True)


def fmt_money(v):
    for unit, size in (("T", 1e12), ("B", 1e9), ("M", 1e6), ("K", 1e3)):
        if v >= size:
            return f"${v / size:.3g}{unit}"
    return f"${v:.3g}"


def main():
    work, models = sys.argv[1], sys.argv[2]
    manifest = json.load(open(os.path.join(models, "manifest.json")))
    assets = manifest["Assets"]
    by_cat = defaultdict(list)
    for a in assets:
        by_cat[a["Category"]].append(a)

    for cat, entries in sorted(by_cat.items()):
        contact_sheet(entries, os.path.join(models, cat, "_preview.png"), work)
        print("sheet", cat, len(entries))

    icons_dir = os.path.join(models, "UI", "Icons")
    icons = sorted(f[:-4] for f in os.listdir(icons_dir) if f.endswith(".png") and not f.startswith("_")) if os.path.isdir(icons_dir) else []

    lines = [
        "# Hamster Plaza - Asset Index",
        "",
        "Generated by `tools/build_asset_index.py` from `manifest.json` - do not edit by hand.",
        "Rebuild the whole library with `tools/build_models.sh` (see [README.md](README.md)).",
        "",
        f"**{len(assets)} unique models** + **{len(icons)} UI icons**. Every model has a Roblox file (`.rbxm`), a 3D file (`.glb`, except particle effects) and `metadata.json`.",
        "",
        "| Category | Models |",
        "|---|---|",
    ]
    for cat, entries in sorted(by_cat.items()):
        lines.append(f"| [{cat}]({cat.replace(' ', '%20')}/_preview.png) | {len(entries)} |")
    lines.append(f"| [UI/Icons](UI/Icons/_contact_sheet.png) | {len(icons)} icons (PNG) |")
    lines.append("")

    for cat, entries in sorted(by_cat.items()):
        lines += [f"## {cat}", "", f"![{cat}]({cat}/_preview.png)", ""]
        if cat.startswith("Hamsters/"):
            lines += ["| Asset | Name in game | Id | Price | Income/s | Spawn chance | Speed | From rebirth | Parts |",
                      "|---|---|---|---|---|---|---|---|---|"]
            for a in sorted(entries, key=lambda e: e["PurchasePrice"]):
                lines.append(
                    f"| [{a['Name']}]({cat}/{a['Name']}/) | {a['DisplayName']} | `{a['HamsterId']}` | {fmt_money(a['PurchasePrice'])} "
                    f"| {fmt_money(a['IncomePerSecond'])} | {a['SpawnChance'] * 100:.4g}% | {a['MovementSpeed']} | {a['MinRebirth']} | {a['Parts']} |")
        else:
            lines += ["| Asset | Size (studs, X x Y x Z) | Parts | Built by | Notes |", "|---|---|---|---|---|"]
            for a in entries:
                size = " x ".join(f"{v:g}" for v in a["SizeStuds"])
                notes = a.get("Notes", "")
                if a.get("FloorName"):
                    notes = f"{a['FloorName']} - {a.get('Purpose', '')}; unlocks at rebirth {a.get('UnlocksAtRebirth')}. " + notes
                lines.append(f"| [{a['Name']}]({cat}/{a['Name']}/) | {size} | {a['Parts']} | `{a['Source']}` | {notes} |")
        lines.append("")

    lines += ["## UI/Icons", "", "![icons](UI/Icons/_contact_sheet.png)", "",
              "Drawn from `src/ReplicatedStorage/Modules/IconShapes.luau` (the game draws the same shapes with Frames). "
              "PNG, 256 x 256, transparent background.", "", ", ".join(f"`{i}`" for i in icons), ""]
    if manifest.get("Duplicates"):
        lines += ["## Skipped duplicates", "", "| Asset | Same as |", "|---|---|"]
        for d in manifest["Duplicates"]:
            lines.append(f"| {d['Category']}/{d['Name']} | {d['SameAs']} |")
        lines.append("")
    open(os.path.join(models, "ASSET_INDEX.md"), "w").write("\n".join(lines))
    print("index:", len(assets), "assets")


if __name__ == "__main__":
    main()
